### PR TITLE
[x11-themes/capitaine-xcursors] fix for building on inkscape v1.0

### PR DESCRIPTION
**Pull request by anktx**

### CODE REVIEW

**Comment by beatussum** [comment]
Thanks! :+1:

**Comment by beatussum** [comment]
I've done some changes from your pull request:
- change the name of the patch files
- patch file suffix: _.diff_ → _.patch_
- reformat the ebuild: replace space by tabulation
- add some useless stuff in the header of the patch files :smile:
- replace `--export-filename` with the short option `-o`
- add `dbus-run-session` to avoid all warnings about **D-Bus**

**Comment by anktx** [comment]
Thanks, I saw this in commits. I will consider for the future. Thanks again for your repository!

**Comment by beatussum** [comment]
You're welcome! 😄

**Pull request closed without merging**
